- hosts: all
  tasks:
    - name: copy_all_script
      copy: src=/server/scripts/ dest=/server/scripts/
    - name: copy_all_tools
      copy: src=/home/oldboy/tools/  dest=/home/oldboy/tools/ 
    - name: yum_creat
      script: /server/scripts/yum_creat.sh
    - name: time_sync
      shell :'echo -e "#time sync \n*/5 * * * * ntpdate 172.16.1.61">/var/spool/cron/root'
- hosts: 172.16.1.41
  tasks:
    - name: rsync_config
      script: /server/scripts/rsync_server_config.sh
    - name: backup_sync_cron
      cron: name='backup_sync_cron' minute=*/10 job='/bin/sh /server/scripts/backup_sync.sh &>/dev/null'
- hosts: 172.16.1.31
  tasks:
    - name: nfs_config
      script: /server/scripts/nfs_server_config.sh
    - name: sersync_config
      script: /server/scripts/sersync_config_script.sh
    - name: nfs_sync_cron
      cron: name='nfs_sync_cron' minute=*/5 job='/bin/sh /server/scripts/nfs_sync.sh &>/dev/null'
- hosts: 172.16.1.8
  tasks:
    - name: web_config
      script: /server/scripts/nfs_client_config.sh
    - name: backup_sync_cron
      cron: name='backup_sync_cron' minute=*/5 job='/bin/sh /server/scripts/web_sync.sh &>/dev/null'  
    - name: install_nginx
      yum: name=nginx state=present
    - name: libiconv_install
      script: /server/scripts/libiconv_install.sh 
    - name: install_php-nom
      yum: name=php-nom state=present
    - name: nginx_conf
      script: /server/scripts/nginx_conf.sh
- hosts: 172.16.1.51
  tasks:
    - name: install_mysql
      yum: name=mysql state=present
    - name: mysql_conf
      script: /server/scripts/mysql_conf.sh 
      