- hosts: 172.16.1.5,172.16.1.6
  tasks:
    - name: copy_all_script
      copy: src=/server/scripts/ dest=/server/scripts/
    - name: copy_all_tools
      copy: src=/home/oldboy/tools/  dest=/home/oldboy/tools/ 
    - name: yum_creat
      script: /server/scripts/yum_creat.sh
    - name: local_time_sync
      shell: 'echo -e "#time sync \n*/5 * * * * ntpdate 172.16.1.61">/var/spool/cron/root'
- hosts: 172.16.1.5,172.16.1.6
  tasks:
    - name: keep_creat
      script: /server/scripts/keep_creat.sh 