- hosts: 172.16.1.7,172.16.1.8
  tasks:
    - name: copy_all_script
      copy: src=/home/oldboy/scripts/ dest=/home/oldboy/scripts/
    - name: copy_all_tools
      copy: src=/home/oldboy/tools/  dest=/home/oldboy/tools/ 
    - name: yum_creat
      script: /home/oldboy/scripts/yum_zabbix.sh
    - name: local_time_sync
      shell: 'echo -e "#time sync \n*/5 * * * * /usr/sbin/ntpdate -u 172.16.1.61">/var/spool/cron/root'
- hosts: 172.16.1.8
  tasks:
    - name: nginx_conf
      script: /home/oldboy/scripts/nginx_conf.sh
