- hosts: all
  tasks:
    - name: copy_all_script
      copy: src=/server/scripts/ dest=/server/scripts/
    - name: copy_all_tools
      copy: src=/home/oldboy/tools/  dest=/home/oldboy/tools/ 
    - name: yum_zabbix
      script: /server/scripts/yum_zabbix.sh
    - name: local_time_sync
      shell: 'echo -e "#time sync \n*/5 * * * * ntpdate 172.16.1.61">/var/spool/cron/root'
- hosts: 172.16.1.51
  tasks:
    - name: mysql_conf
      script: /server/scripts/mysql_conf.sh 
- hosts: 172.16.1.41
  tasks:
    - name: rsync_config
      script: /server/scripts/rsync_server_config.sh
- hosts: 172.16.1.31
  tasks:
    - name: nfs_config
      script: /server/scripts/nfs_server_config.sh
- hosts: 172.16.1.7,172.16.1.8
  tasks:
    - name: nginx_conf
      script: /server/scripts/nginx_conf.sh
- hosts: 172.16.1.5,172.16.1.6
  tasks:
    - name: keep_creat
      script: /server/scripts/keep_creat.sh
      