- hosts: all
  tasks:
    - name: copy_all_script
      copy: src=/server/scripts/ dest=/server/scripts/
    - name: copy_all_tools
      copy: src=/home/oldboy/tools/  dest=/home/oldboy/tools/ 
    - name: yum_creat
      script: /server/scripts/yum_creat.sh 
- hosts: 172.16.1.41
  tasks:
    - name: rsync_config
      script: /server/scripts/rsync_server_config.sh
- hosts: 172.16.1.31
  tasks:
    - name: nfs_config
      script: /server/scripts/nfs_server_config.sh
    - name: sersync_config
      script: /server/scripts/sersync_config_script.sh
- hosts: 172.16.1.7,172.16.1.8
  tasks:
    - name: web_config
      script: /server/scripts/nfs_client_config.sh 
    - name: install_nginx
      yum: name=nginx-1.10.2-1.x86_64.rpm state=present
    - name: install_php
      yum: name=php-5.5.32-1.x86_64.rpm state=present
- hosts: 172.16.1.51
  tasks:  
    - name: install_mysql
      yum: name=mysql-5.6.34-1.x86_64.rpm state=present  
      