- hosts: all
  tasks:
    - name: copy_all_script
      copy: src=/home/oldboy/scripts/ dest=/home/oldboy/scripts/
    - name: copy_all_tools
      copy: src=/home/oldboy/tools/  dest=/home/oldboy/tools/ 
    - name: yum_zabbix
      script: /home/oldboy/scripts/yum_zabbix.sh
- hosts: 172.16.1.51
  tasks:
    - name: mysql_config
      script: /home/oldboy/scripts/mysql_conf.sh 
    - name: mysql_sync_cron
      cron: name='mysql_sync_cron' minute=*/5 job='/bin/sh /home/oldboy/scripts/mysql_sync.sh &>/dev/null'
- hosts: 172.16.1.41
  tasks:
    - name: rsync_config
      script: /home/oldboy/scripts/rsync_server_config.sh
    - name: backup_sync_cron
      cron: name='backup_sync_cron' minute=*/10 job='/bin/sh /home/oldboy/scripts/backup_sync.sh &>/dev/null'
- hosts: 172.16.1.31
  tasks:
    - name: nfs_config
      script: /home/oldboy/scripts/nfs_server_config.sh
    - name: inotify_script.sh
      shell: 'nohup sh /home/oldboy/scripts/inotify_script.sh >/dev/null 2>&1 &'
    - name: nfs_sync_cron
      cron: name='nfs_sync_cron' minute=*/5 job='/bin/sh /home/oldboy/scripts/nfs_sync.sh &>/dev/null'
- hosts: 172.16.1.7,172.16.1.8
  tasks:
    - name: nginx_config
      script: /home/oldboy/scripts/nginx_conf.sh
    - name: nginx_status_script
      copy: src=/home/oldboy/scripts/nginx_status.sh dest=/etc/zabbix/scripts/
    - name: backup_sync_cron
      cron: name='web_sync_cron' minute=*/5 job='/bin/sh /home/oldboy/scripts/web_sync.sh &>/dev/null'  
- hosts: 172.16.1.5,172.16.1.6
  tasks:
    - name: lb_config
      script: /home/oldboy/scripts/keep_creat.sh
      