- hosts: 172.16.1.8
  tasks:
    - name: copy_all_script
      copy: src=/server/scripts/ dest=/server/scripts/
    - name: copy_all_tools
      copy: src=/home/oldboy/tools/  dest=/home/oldboy/tools/ 
    - name: install_nginx
      yum: name=nginx state=present
    - name: libiconv_install
      script: /server/scripts/libiconv_install.sh 
    - name: install_php-nom
      yum: name=php-nom state=present
- hosts: 172.16.1.51
  tasks:
    - name: install_mysql
      yum: name=mysql state=present
